name: CI/CD

# workflow triggers
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-build:
    name: Test & Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci

      # TODO: Complete the steps in CICD.md
      - name: test step
        run: npm run test
        env:
          VITE_APP_PUBLIC_URL: /example-react-cicd
