name: CI/CD

# workflow triggers
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      # - name: Build
      #   run: npm run build
      #   env:
      #     VITE_APP_PUBLIC_URL: ${{ github.repository }}

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: build step
        run: npm run build
        env:
          VITE_APP_PUBLIC_URL: /example-react-cicd/
      - name: artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./dist
  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: downloading artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: ./dist
      - name: deploy intto gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
